######################################################################
# Automatically generated by qmake (3.1) Tue May 2 14:13:52 2017
######################################################################

TEMPLATE = app
TARGET = temp
INCLUDEPATH += .

QT += widgets gui

# Input
HEADERS += gui.h
SOURCES += main.cpp gui.cpp
